# Window
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 360

# Colors
COLOR_ORANGE = (255, 128, 0)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

# Menu
MENU_OPTIONS = (
    "NEW GAME (1 PLAYER)",
    "NEW GAME (2 PLAYERS - COOPERATIVE)",
    "NEW GAME (2 PLAYERS - COMPETITIVE)",
    "SCORE",
    "QUIT",
)
